//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.ApiErrorResource", typeof(ApiErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while deleting database entity..
        /// </summary>
        public static string RepositoryBaseException_Delete {
            get {
                return ResourceManager.GetString("RepositoryBaseException_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while getting database entities..
        /// </summary>
        public static string RepositoryBaseException_GetAll {
            get {
                return ResourceManager.GetString("RepositoryBaseException_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while getting database entity..
        /// </summary>
        public static string RepositoryBaseException_GetById {
            get {
                return ResourceManager.GetString("RepositoryBaseException_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while inserting database entity..
        /// </summary>
        public static string RepositoryBaseException_Insert {
            get {
                return ResourceManager.GetString("RepositoryBaseException_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while saving database entities..
        /// </summary>
        public static string RepositoryBaseException_Save {
            get {
                return ResourceManager.GetString("RepositoryBaseException_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while updating database entity..
        /// </summary>
        public static string RepositoryBaseException_Update {
            get {
                return ResourceManager.GetString("RepositoryBaseException_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To do task does not exist..
        /// </summary>
        public static string ValidationException_TaskDoesNotExist {
            get {
                return ResourceManager.GetString("ValidationException_TaskDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string ValidationException_UserDoesNotExist {
            get {
                return ResourceManager.GetString("ValidationException_UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated users&apos; email or name have beed found..
        /// </summary>
        public static string ValidationException_UserExist {
            get {
                return ResourceManager.GetString("ValidationException_UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized action by the user..
        /// </summary>
        public static string ValidationException_UserIdentityMissMatch {
            get {
                return ResourceManager.GetString("ValidationException_UserIdentityMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been blocked because of too many failed attemts to login..
        /// </summary>
        public static string ValidationException_UserIsBlocked {
            get {
                return ResourceManager.GetString("ValidationException_UserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users&apos; password is incorrect..
        /// </summary>
        public static string ValidationException_UserPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("ValidationException_UserPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users&apos; reset token is expired..
        /// </summary>
        public static string ValidationException_UserResetPasswordTokenIsExpired {
            get {
                return ResourceManager.GetString("ValidationException_UserResetPasswordTokenIsExpired", resourceCulture);
            }
        }
    }
}
