//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectX - Reset password.
        /// </summary>
        public static string MessageSubject_PasswordReset {
            get {
                return ResourceManager.GetString("MessageSubject_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE&gt;&lt;html&gt;&lt;body&gt;&lt;p style=&quot;Margin-top: 0;Margin-bottom: 0;&quot;&gt;&lt;span style=&quot;color:#000000&quot;&gt;Hi,&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;Margin-top: 20px;Margin-bottom: 0;&quot;&gt;&lt;span style=&quot;color:#000000&quot;&gt;You can reset your password by clicking on this link:&lt;/span&gt;&amp;nbsp;&lt;a style=&quot;text-decoration: underline;transition: opacity 0.1s ease-in;color: #18527c;&quot; href=&quot;http://localhost:65072/api/ResetPassword?token={0}&quot;&gt;password reset&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string MessageTemplate_PasswordReset {
            get {
                return ResourceManager.GetString("MessageTemplate_PasswordReset", resourceCulture);
            }
        }
    }
}
